version: "3.7"

services:
  # Base Image
  # -------------------------------------------------------
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: "base"

  # NGINX Proxy
  # -------------------------------------------------------
  proxy:
    image: nginx:1.17.8
    restart: always
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./config/nginx_prod.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    environment:
      - ENV=development
    depends_on:
      - main-site
      - nextcloud
      - gitlab
    networks:
      - main
      - nextcloud
      - gitlab

  # Main Yesod Site
  # -------------------------------------------------------
  main-site:
    build:
      context: ./main-site
      dockerfile: Dockerfile
    image: "main-site"
    container_name: "main-site"
    networks:
      - main
    ports:
      - 8080:3000
    environment:
      - PORT=$SITE_PORT
      - YESOD_PORT=$SITE_YESOD_PORT
      - SQLITE_DATABASE=$SITE_DATABASE
      - ROBOT_PASS
    volumes:
      - ./main-site/app:/site/app
      - ./main-site/assets:/site/assets
      - ./main-site/config:/site/config
      - ./main-site/Layouts:/site/Layouts
      - ./main-site/src:/site/src
      - ./main-site/static:/site/static
      - ./main-site/templates:/site/templates
      - ./main-site/test:/site/test
      - main-site-db:/site/database/
    stdin_open: true
    entrypoint: ["entrypoint.sh"]

  # Nextcloud
  # -------------------------------------------------------
  nextcloud:
    image: nextcloud:apache
    container_name: "nextcloud"
    restart: always
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=myNextCloudDB
      - MYSQL_USER=myNextCloudUser
      - MYSQL_PASSWORD=$NC_MYSQL_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=$NC_DOMAINS
    ports:
      - 8082:80
    volumes:
      - nextcloud-storage:/var/www/html
    networks:
      - nextcloud
    depends_on:
      - nextcloud-db

  # Nextcloud Database
  # -------------------------------------------------------
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NC_MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=$NC_MYSQL_PASSWORD
      - MYSQL_DATABASE=myNextCloudDB
      - MYSQL_USER=myNextCloudUser
    networks:
      - nextcloud

  # Gitlab
  # -------------------------------------------------------
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: "gitlab.localhost"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
        gitlab_rails['smtp_enable'] = true 
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 465    
        gitlab_rails['smtp_user_name'] = "robot@richardconnorjohnstone.com"
        gitlab_rails['smtp_password'] = $ROBOT_PASS
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true    
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
    ports:
      - 8083:80
      - 8084:443
      - 22:22
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/log/gitlab
      - gitlab-logs:/var/opt/gitlab
    networks:
      - gitlab

networks:
  main:
  nextcloud:
  gitlab:

volumes:
  nextcloud-storage:
  nextcloud-db:
  gitlab-config:
  gitlab-data:
  gitlab-logs:
  main-site-db:
